<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GamesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('games')->insert([
            [
                'name' => 'The Legend of Zelda: Breath of the Wild',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'An epic open-world adventure game that takes place in a vast world filled with challenges and mysteries.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('2017', '03', '03'),
                'platform' => 'Nintendo Switch',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Super Mario Odyssey',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A 3D platformer adventure game featuring Mario and his new friend, Cappy, as they travel across various kingdoms to save Princess Peach.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('2017', '10', '27'),
                'platform' => 'Nintendo Switch',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Animal Crossing: New Horizons',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A life simulation game where players live on a deserted island and create their own paradise by gathering resources, fishing, and interacting with anthropomorphic animals.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('2020', '03', '20'),
                'platform' => 'Nintendo Switch',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mario Kart 8 Deluxe',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A fun and fast-paced kart racing game featuring various characters from the Mario universe.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('2017', '04', '28'),
                'platform' => 'Nintendo Switch',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Super Smash Bros. Ultimate',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A crossover fighting game featuring a vast roster of characters from various Nintendo franchises.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('2018', '12', '07'),
                'platform' => 'Nintendo Switch',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Legend of Zelda: Ocarina of Time',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'An action-adventure game set in a fantasy world, known for its innovative gameplay and immersive storytelling.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('1998', '11', '21'),
                'platform' => 'Nintendo 64',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Metroid Prime',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A first-person adventure game combining action and puzzle-solving elements, set in a sci-fi universe.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('2002', '11', '17'),
                'platform' => 'Nintendo GameCube',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Splatoon 2',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A unique third-person shooter game where players control squid-like characters and battle using colored ink.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('2017', '07', '21'),
                'platform' => 'Nintendo Switch',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fire Emblem: Three Houses',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A tactical role-playing game set in a fantasy world, featuring deep storylines and strategic battles.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('2019', '07', '26'),
                'platform' => 'Nintendo Switch',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Super Mario 64',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A groundbreaking 3D platformer that set new standards for the genre, featuring Mario in an open-world adventure.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('1996', '06', '23'),
                'platform' => 'Nintendo 64',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Donkey Kong Country',
                'logo_url' => '',
                'cover_image_url' => '',
                'description' => 'A classic side-scrolling platformer featuring Donkey Kong and his sidekick Diddy Kong on a quest to recover their stolen banana hoard.',
                'reviews_ids' => json_encode([]),
                'average_score' => null,
                'release_date' => Carbon::create('1994', '11', '21'),
                'platform' => 'Super Nintendo Entertainment System',
                'developer' => 'Nintendo',
                'publisher' => 'Nintendo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
